# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designn.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(150, 10, 191, 241))
        self.widget.setObjectName("widget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 191, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.apples = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.apples.setObjectName("apples")
        self.gridLayout.addWidget(self.apples, 3, 0, 1, 1)
        self.guavas = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.guavas.setObjectName("guavas")
        self.gridLayout.addWidget(self.guavas, 5, 0, 1, 1)
        self.oweis = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.oweis.setObjectName("oweis")
        self.gridLayout.addWidget(self.oweis, 1, 0, 1, 1)
        self.sokary = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sokary.setObjectName("sokary")
        self.gridLayout.addWidget(self.sokary, 2, 0, 1, 1)
        self.bananas = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.bananas.setObjectName("bananas")
        self.gridLayout.addWidget(self.bananas, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 260, 101, 21))
        self.label.setObjectName("label")
        self.kam = QtWidgets.QPushButton(self.centralwidget)
        self.kam.setGeometry(QtCore.QRect(310, 280, 41, 16))
        self.kam.setObjectName("kam")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(340, 10, 160, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.num_oweis = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.num_oweis.setObjectName("num_oweis")
        self.verticalLayout.addWidget(self.num_oweis)
        self.num_sokary = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.num_sokary.setObjectName("num_sokary")
        self.verticalLayout.addWidget(self.num_sokary)
        self.num_apples = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.num_apples.setObjectName("num_apples")
        self.verticalLayout.addWidget(self.num_apples)
        self.num_bananas = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.num_bananas.setObjectName("num_bananas")
        self.verticalLayout.addWidget(self.num_bananas)
        self.num_guavas = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.num_guavas.setObjectName("num_guavas")
        self.verticalLayout.addWidget(self.num_guavas)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.apples.setText(_translate("MainWindow", "Apples"))
        self.guavas.setText(_translate("MainWindow", "Guavas"))
        self.oweis.setText(_translate("MainWindow", "oweis"))
        self.sokary.setText(_translate("MainWindow", "sokary"))
        self.bananas.setText(_translate("MainWindow", "Bananas"))
        self.label.setText(_translate("MainWindow", "Total Cost : 0"))
        self.kam.setText(_translate("MainWindow", "kam"))
        self.num_oweis.setText(_translate("MainWindow", "0"))
        self.num_sokary.setText(_translate("MainWindow", "0"))
        self.num_apples.setText(_translate("MainWindow", "0"))
        self.num_bananas.setText(_translate("MainWindow", "0 "))
        self.num_guavas.setText(_translate("MainWindow", "0"))
